# Prework Assignment

### General Background Questions

1. Why is version control important in science?

In [1]:
print("Although universally important, version control is especially important in science as it allows multiple users to contribute to the same documents at once. It also holds key features that allow for smooth operations, such as commit logs.")

Version control is a universally important and convenient tool for all. However, it is especially important in science as it holds significant contribution to the progression of research. Version control offers many conveniences such as allowing changes from multiple users


2. What kind of research artifacts can we track with Git?

In [1]:
print("We can track manuscripts, notes, datasets, and statisfical codes/figures")

3. What are the three main things that can go wrong in a data science project?

In [26]:
goWrong = {1:"The model doesn't work well", 2:"You weren't solving the right problem", 3:"The data aren't what you wanted"}

def problemList(n):
    for k,v in n.items():
        print(str(k) + ": " + v)
        
problemList(goWrong)

1: The model doesn't work well
2: You weren't solving the right problem
3: The data aren't what you wanted


# Python Background Questions

These short exercises are a way to familiarize yourself with python. If you find these exercises too difficult, don’t worry! We will review the basics the first day to make sure we are all comfortable coding in Python.

Please save your work in this document and `git push` them to the `prework-assignment` repo.

----------------------------------------------------------------

### Problem 1: Basic Operations

You are at Vanessa's Vegan Cafe and you loved it so much you wanna leave a tip. Write a function that takes the amount owed and calculates how much money you pay with an 18% tip. If functions still scare you, just the solution code will do.

In [42]:
def tipCalculator():
    print("How much did your bill come out to?")
    x = float(input())
    bill = round((x * 1.18),2)
    print(bill)

tipCalculator()

How much did your bill come out to?
1120413.2312351451
1322087.61


----------------------------------------------------------------

### Problem 2: Lists

I have a fortune cookie that says my lucky numbers are:

       [23, 54, 6, 8, 10078, 3]

Write a function that returns 3 lists (if functions still scare you, just the solution code will do)
   - replace the number 6 with 1
   - the above list in decreasing order
   - all values greater than 15

In [75]:
luckyNumbers = [23, 54, 6, 8, 10078, 3]


def threeLists():
    luckyNumbers[2] = 1
    print(luckyNumbers)

    luckyNumbers.sort(reverse = True)
    print(luckyNumbers)

    greaterThan = []
    for i in luckyNumbers:
        if i > 15:
            greaterThan.append(i)
    print(greaterThan)

threeLists()

[23, 54, 1, 8, 10078, 3]
[10078, 54, 23, 8, 3, 1]
[10078, 54, 23]


----------------------------------------------------------------

### Problem 3: Basic Operations

Let's now take the first step in coding some real data science. Write a statement that loads the `numpy` library into the interpreter and gives it an alias of `np`.

In [77]:
import numpy as np

----------------------------------------------------------------

### Problem 4: Numpy

Generated a 10x10 `numpy` array with random numbers and slice the array to get the 2nd and 3rd column. Also calculate the average of 6th column using `numpy`.

In [96]:
x = np.random.randint(0, 10, (10,10))

secondColumn = x[:,1]
thirdColumn = x[:,2]

sixthColumn = x[:,5]
def colAvg():
    acc = 0
    rsf = 0
    for i in x[:,5]:
        rsf = rsf + i
        acc += 1
    print(rsf/acc)
print(secondColumn)
print(thirdColumn)

print(sixthColumn)
colAvg()

[4 6 1 5 1 3 7 7 1 1]
[1 3 1 8 9 5 3 0 1 3]
[6 0 0 8 9 6 9 8 1 8]
5.5


----------------------------------------------------------------

##### That's it! We look forward to seeing you in class!